#!/bin/bash

set -eou pipefail
SECRET=$1
CMD="bash --init-file <(echo \"PS1='Editing $SECRET $ '; alias cd='echo When done exit this shell to persist changes';\") || true"
kexecutesecrets $SECRET $CMD

